Update rcngzd

diff --git a/rcngzd b/rcngzd
--- a/rcngzd
+++ b/rcngzd
@@ -2,22 +2,28 @@
 #Análisis completo del target
 #Script para facilitar análisis.
 
-trap exity EXIT
 
-function exity(){
-	echo ""
-	echo "[*] Aborting [*]"
+
+trap exity SIGINT
+
+exity(){
 	echo " "
+	echo "$(tput setaf 3)[$(tput setaf 1)!$(tput setaf 3)]Saliendo ..."
+	service apache2 stop
+	sleep 1
+	echo " "
+	echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Thanks!"
+	echo " "
+	exit
 }
 
 #rcngzd <ip> 
 
 #Variable para settear el root.
-ktb=`whoami`
 
 if [[ $EUID != 0 ]] ; then
 	echo " "
-	echo "$(tput setaf 1)[!] NO ROOT ABORTING [!]"
+	echo "$(tput setaf 1)$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]NECESITAS SER ROOT."
 	echo " "
 	exit
 fi
@@ -27,8 +33,15 @@ fi
 #Reconocimiento de parámetro <ip>
 
 if [[ -z $1 ]] ; then
+	echo "$(tput setaf 105)" ; figlet Recognizement
+	echo "$(tput setaf 6) "
+	echo "V3rs10n $(tput setaf 1)1.6.5"
 	echo " "
-	echo "rcngz <ip>"
+	echo "$(tput setaf 6)rcngzd m4d3 by [$(tput setaf 3)ShadowVMX$(tput setaf 6)] --> $(tput setaf 1)https://github.com/ShadowVMX"
+	sleep 1
+	echo " "
+	echo " "
+	echo "$(tput setaf 6)[$(tput setaf 1)-$(tput setaf 6)]rcngz $(tput setaf 1)<ip>"
 	echo " "
 	exit
 fi
@@ -36,26 +49,22 @@ fi
 #------------------------------------------
 #
 #Comprobación de Whichsystem && extractports
-echo "$(tput setaf 1) "
-echo "___________________________________________________________________"
-echo "___________________________________________________________________"
+
 echo " "
-echo "R3c0gn1z3m3nt Pr0c3ss"
-echo " "
-echo "V3rs10n 1.1.5"
-echo " "
-echo "rcngzd made by [ShadowVMX] --> https://github.com/ShadowVMX"
-echo " "
-echo "___________________________________________________________________"
-echo "___________________________________________________________________"
-echo "$(tput setaf 2) "
-sleep 3
+echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Verificando componentes en su sistema..."
+sleep 1
+
 
 ls -l /usr/bin/Whichsystem &> /dev/null
 
+
+echo " "
+echo " "
+sleep 1
+
 if [[ $? == 0 ]] ; then 
 	echo " "
-	echo "[!]Whichsystem ya está en su sistema, abortando descarga.[!]"
+	echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Whichsystem ya está en su sistema, abortando descarga."
 	echo " "
 else
 	git clone https://github.com/ShadowVMX/Whichsystem.git &> /dev/null
@@ -63,53 +72,58 @@ else
 	cp Whichsystem/Whichsystem /usr/bin/
 
 	echo " "
-	echo "[!] Whichsystem descargado en su sistema.[!]"
+	echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Whichsystem descargado en su sistema."
 	echo " "
-	echo "[!]Podrá usar la herramienta directamente en su sistema --> Whichsystem <ip>"
+	echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Podrá usar la herramienta directamente en su sistema --> Whichsystem <ip>"
 	echo " "
 	echo "ctrl_c para cerrar cuando vea el código."
 	echo " "
-	xterm -e zsh -c "nano /usr/bin/Whichsystem"
 fi
 
-#Quien quiera tenerlo en la bashrc que descomente, si lo quiere en la zshrc modificar y descomentar.
 
-#cat /root/.bashrc | grep "extractports" &> /dev/null
+#--------------------------------------------------------------
+#
+#Instalación extracports
+#
+sleep 1.5
 
-#if [[ $? = "0" ]] ; then
-#	echo " "
-#	echo "[!]extractports ya está descargado en su sistema.[!]"
-#else
-#	git clone https://github.com/ShadowVMX/extractports.git &> /dev/null
-#	echo " "
-#	cat extractports/extractports >> /root/.bashrc
-#	echo "[!] extractports descargándose en el sistema. [!]"
-#	echo " "
-#	sleep 2
-#	echo "[+++] Actualizando base de datos [+++]"
-#	echo " "
-#	updatedb &> /dev/null
-#	echo "[!] Completado [!]"
-#	echo " "
-#fi
+ls -l /usr/bin/extractports &> /dev/null
+
+if [[ $? == 0 ]] ; then 
+        echo " "
+        echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Extractports ya está en su sistema, abortando descarga."
+        echo " "
+else
+        git clone https://github.com/ShadowVMX/extractports.git &> /dev/null
+        chmod +x extractports/extractports 
+        cp extractports/extractports /usr/bin/
+
+        echo " "
+        echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Extractports descargado en su sistema."
+        echo " "
+        echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Podrá usar la herramienta directamente en su sistema --> extractports + <captura grepeable nmap>"
+        echo " "
+fi
+
+sleep 1.5
 
 #---------------------------------------------------------------
 #
 #Uso herramienta Whichsystem
 #
 
-echo " "
+echo "$(tput setaf 5) "
 echo "___________________________________________________________________"
 echo "___________________________________________________________________"
-echo " "
+echo "$(tput setaf 6) "
+
 Whichsystem $1
 
 echo " "
-echo "[!]Reporte de S.O objetivo completo.[!]"
+echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Reporte de S.O objetivo completo.[!]"
 echo " "
-sleep 2
 
-echo " "
+echo "$(tput setaf 5)"
 echo "___________________________________________________________________"
 echo "___________________________________________________________________"
 echo " "
@@ -118,8 +132,20 @@ sleep 1
 
 #Usando nmap para generar allports 1 y 2 según análisis exhaustivo.
 echo " "
-echo "[X] Escaneando [X]"
+echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Escaneando todos los puertos abiertos posibles ..."
 nmap -sS --min-rate 5000 -n $1 -oG allports &> /dev/null
+
+echo "$(tput setaf 5)"
+#---Parseo de información con extractports---#
+
+extractports allports
+
+echo "$(tput setaf 5)"
+echo "___________________________________________________________________"
+echo "___________________________________________________________________"
+echo "$(tput setaf 6) "
+
+
 nmap -sS --min-rate 5000 -n $1 -oX allports.xml &> /dev/null
 xsltproc allports.xml -o weburl.html &> /dev/null
 
@@ -136,42 +162,42 @@ cp weburl.html /var/www/html/index.html &> /dev/null
 WebS=`hostname -I`
 
 echo " "
-echo "[!]Abra el navegador --> http://localhost"
-echo " "
+echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Abra el navegador --> $(tput setaf 1)http://localhost"
+echo "$(tput setaf 6) "
 
 #Dar ventaja al usuario para que procese.
 cat allports | grep "23/open/tcp//telnet//" &> /dev/null
 if [[ $? = 0 ]] ; then
         echo " "
-        echo "[!] t3ln3t --> try t3ln3t <ip> [!]"
+        echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]telnet --> try telnet <ip>"
         echo " "
 fi
 
 cat allports | grep "80/open/tcp//http//" &> /dev/null
 if [[ $? = 0 ]] ; then
 	echo " "
-	echo "[!] url --> http://$1 [!]"
+	echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]url --> http://$1"
 	echo " "
 fi
 
 cat allports | grep "21/open/tcp//ftp//" &> /dev/null
 if [[ $? = 0 ]] ; then
         echo " "
-        echo "[!] ftp --> try 4n0nym0us l0gin [!]"
+        echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]ftp --> try [user:anonymoys] [pass:empty/vacía]"
         echo " "
 fi
 
 cat allports | grep "445/open/tcp//microsoft-ds//" &> /dev/null
 if [[ $? = 0 ]] ; then
         echo " "
-        echo "[!] smb --> try smbm4p -H <ip> | smbcli3nt -L <ip> | cr4ckm4p3x3c | smbm4p | 3vil-winrm | pk3x3c [!]"
+        echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]smb --> try [smbclient -L //<ip>] | smbmap -H <ip> | crackmapexec smb <ip>"
         echo " "
 fi
 
 cat allports | grep "3306/open/tcp//ftp//" &> /dev/null
 if [[ $? = 0 ]] ; then
         echo " "
-        echo "[!] mysql (3306) --> mysql -u 'username' -h <ip> -p'passw0rd' [!]"
+        echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]mysql (3306) --> mysql -u 'username' -h <ip> -p'password'"
         echo " "
 fi
 
@@ -179,21 +205,21 @@ fi
 cat allports | grep "8080/open/tcp//ftp//" &> /dev/null
 if [[ $? = 0 ]] ; then
         echo " "
-        echo "[!] http://$1:8080 --> 0p3n URL [!]"
+        echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]http://$1:8080 --> Open URL"
         echo " "
 fi
 
 cat allports | grep "22/open/tcp//ftp//" &> /dev/null
 if [[ $? = 0 ]] ; then
         echo " "
-        echo "[!] ssh --> N0thing y0u c4n d0 ... 4n0w. [!]"
+        echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]ssh --> Verifica versión con exploitdb (searchsploit) e intenta sacar usuarios si es old version."
         echo " "
 fi
 
 cat allports | grep "1337/open/tcp//ftp//" &> /dev/null
 if [[ $? = 0 ]] ; then
         echo " "
-        echo "[!] B4ckd00r [!]"
+        echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Posible backdoor."
         echo " "
 fi
 
@@ -201,12 +227,12 @@ fi
 
 #Continua el escaneo
 
-nmap -p"-" --open -T5 -n $1 -oG allports2 &> /dev/null 
+#nmap -p"-" --open -T5 -n $1 -oG allports2 &> /dev/null 
 echo " "
 nmap -sU --min-rate 5000 -n $1 -oG allportsUDP &> /dev/null
-echo "[!]Archivos allports generados.[!]"
+echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Archivos allports (TCP/UDP) generados."
 
-echo " "
+echo "$(tput setaf 5) "
 echo "___________________________________________________________________"
 echo "___________________________________________________________________"
 echo " "
@@ -218,11 +244,11 @@ sleep 2
 nmap -sCV --min-rate 5000 -n $1 -oN targeted &> /dev/null
 
 echo " "
-echo "[!]Archivo targeted generado.[!]"
+echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Archivo targeted generado."
 echo " "
 sleep 2
 
-echo " "
+echo "$(tput setaf 5) "
 echo "___________________________________________________________________"
 echo "___________________________________________________________________"
 echo " "
@@ -234,28 +260,28 @@ RKT=`cat allports | tr " " "\n" | grep "^80" | cut -d "/" -f1 | head -1`
 if [[ $RKT = 80 ]] ; then
 	whatweb http://$1/ > kyndofweb
 	echo " "
-	echo "[!]Kyndofweb generado.[!]"
+	echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Kyndofweb generado."
 	echo " "
-	echo " "
+	echo "$(tput setaf 5) "
 echo "___________________________________________________________________"
 echo "___________________________________________________________________"
 echo " "
 	sleep 2
 	echo " "
-	echo "[!]Fuerza bruta contra subdirectorios.[!]"
+	echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Fuerza bruta contra subdirectorios."
 	echo " "
 	gobuster dir -w /usr/share/wordlists/dirb/common.txt -u http://$1 > subdirect 2> /dev/null
 	
-	echo " "
+	echo "$(tput setaf 5) "
 echo "___________________________________________________________________"
 echo "___________________________________________________________________"
 echo " "	
 
-	echo "[!]Completado.[!]"
+	echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Completado."
 	echo " "
 
 else
-	echo "[!]No web on target.[!]"
+	echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]No web on target."
 	echo " "
 fi
 
@@ -272,7 +298,7 @@ rm -f allports.xml &> /dev/null
 #Aviso final
 
 echo " "
-echo "[!] Todo el reporte podrá ser visualizado en la carpeta actual con ls -l [!]"
+echo "$(tput setaf 6)[$(tput setaf 1)!$(tput setaf 6)]Todo el reporte podrá ser visualizado en la carpeta actual con ls -l."
 echo " "
 
 #-----------------FIN-------------------#
